In [2]:
import pickle

In [3]:
#dates_file = open('dates.pickle', 'wb')
#pickle.dump(dates_dataset, dates_file)
#dates_file.close()

dates_file = open('dataset/dates.pickle', 'rb')
dates = pickle.load(dates_file)
dates_file.close()

In [4]:
dates

[('9 may 1998', '1998-05-09'),
 ('10.09.70', '1970-09-10'),
 ('4/28/90', '1990-04-28'),
 ('thursday january 26 1995', '1995-01-26'),
 ('monday march 7 1983', '1983-03-07'),
 ('sunday may 22 1988', '1988-05-22'),
 ('tuesday july 8 2008', '2008-07-08'),
 ('08 sep 1999', '1999-09-08'),
 ('1 jan 1981', '1981-01-01'),
 ('monday may 22 1995', '1995-05-22'),
 ('friday june 16 1978', '1978-06-16'),
 ('friday june 18 1999', '1999-06-18'),
 ('8 oct 1987', '1987-10-08'),
 ('tuesday april 1 2008', '2008-04-01'),
 ('6 september 2012', '2012-09-06'),
 ('12 november 1981', '1981-11-12'),
 ('friday august 19 2011', '2011-08-19'),
 ('25 08 07', '2007-08-25'),
 ('18 september 1982', '1982-09-18'),
 ('friday february 25 1994', '1994-02-25'),
 ('friday march 19 1976', '1976-03-19'),
 ('20.02.06', '2006-02-20'),
 ('17.01.98', '1998-01-17'),
 ('october 24 2009', '2009-10-24'),
 ('17 apr 2004', '2004-04-17'),
 ('03.05.81', '1981-05-03'),
 ('31 jan 1980', '1980-01-31'),
 ('01 jan 1984', '1984-01-01'),
 ('19 apr 1975', '1975-04-19'),
 ('sunday december 5 1982', '1982-12-05'),
 ('tuesday march 30 1993', '1993-03-30'),
 ('sunday december 1 1991', '1991-12-01'),
 ('08.08.71', '1971-08-08'),
 ('march 23 2001', '2001-03-23'),
 ('sunday february 7 1993', '1993-02-07'),
 ('saturday october 30 1971', '1971-10-30'),
 ('saturday october 2 2004', '2004-10-02'),
 ('1/1/17', '2017-01-01'),
 ('10 april 1998', '1998-04-10'),
 ('friday march 27 1970', '1970-03-27'),
 ('6/15/70', '1970-06-15'),
 ('7 mar 2015', '2015-03-07'),
 ('february 23 1981', '1981-02-23'),
 ('23.06.09', '2009-06-23'),
 ('4 mar 1982', '1982-03-04'),
 ('7/2/89', '1989-07-02'),
 ('10/9/76', '1976-10-09'),
 ('may 28 2014', '2014-05-28'),
 ('wednesday march 18 1998', '1998-03-18'),
 ('16 mar 1977', '1977-03-16'),
 ('sunday may 15 2016', '2016-05-15'),
 ('monday may 4 2009', '2009-05-04'),
 ('thursday may 13 1982', '1982-05-13'),
 ('9 july 1995', '1995-07-09'),
 ('30 oct 1985', '1985-10-30'),
 ('friday august 19 2005', '2005-08-19'),
 ('july 23 2010', '2010-07-23'),
 ('13 jun 1992', '1992-06-13'),
 ('wednesday september 27 1972', '1972-09-27'),
 ('23.10.85', '1985-10-23'),
 ('saturday february 25 1978', '1978-02-25'),
 ('monday december 22 2003', '2003-12-22'),
 ('22 sep 1984', '1984-09-22'),
 ('10 10 07', '2007-10-10'),
 ('july 29 2015', '2015-07-29'),
 ('tuesday august 24 1982', '1982-08-24'),
 ('jul 17 1987', '1987-07-17'),
 ('wednesday january 20 2010', '2010-01-20'),
 ('wednesday july 7 1999', '1999-07-07'),
 ('07 apr 2005', '2005-04-07'),
 ('thursday november 2 1978', '1978-11-02'),
 ('29.10.72', '1972-10-29'),
 ('3 march 1981', '1981-03-03'),
 ('july 4 1990', '1990-07-04'),
 ('friday august 21 1970', '1970-08-21'),
 ('monday march 24 1980', '1980-03-24'),
 ('04 aug 1985', '1985-08-04'),
 ('19 oct 1993', '1993-10-19'),
 ('9 sep 2006', '2006-09-09'),
 ('friday april 9 1993', '1993-04-09'),
 ('sep 6 1980', '1980-09-06'),
 ('monday april 8 1996', '1996-04-08'),
 ('monday january 13 1992', '1992-01-13'),
 ('11/16/70', '1970-11-16'),
 ('thursday may 10 1973', '1973-05-10'),
 ('friday february 22 1974', '1974-02-22'),
 ('sunday april 16 2000', '2000-04-16'),
 ('7 may 1975', '1975-05-07'),
 ('thursday may 30 1996', '1996-05-30'),
 ('saturday march 20 1982', '1982-03-20'),
 ('monday october 19 1970', '1970-10-19'),
 ('tuesday january 10 1995', '1995-01-10'),
 ('8/27/84', '1984-08-27'),
 ('mar 9 2016', '2016-03-09'),
 ('nov 16 2004', '2004-11-16'),
 ('april 9 1978', '1978-04-09'),
 ('19 september 2002', '2002-09-19'),
 ('april 26 2012', '2012-04-26'),
 ('sunday march 10 1974', '1974-03-10'),
 ('thursday december 10 1970', '1970-12-10'),
 ('8/9/12', '2012-08-09'),
 ('june 20 2003', '2003-06-20'),
 ('monday march 2 1992', '1992-03-02'),
 ('friday july 8 2011', '2011-07-08'),
 ('august 21 1998', '1998-08-21'),
 ('1 jun 2007', '2007-06-01'),
 ('tuesday september 20 1983', '1983-09-20'),
 ('16 oct 1994', '1994-10-16'),
 ('9 02 15', '2015-02-09'),
 ('jul 15 2017', '2017-07-15'),
 ('2/15/78', '1978-02-15'),
 ('16 november 2007', '2007-11-16'),
 ('08 mar 1980', '1980-03-08'),
 ('friday june 13 1975', '1975-06-13'),
 ('5 09 03', '2003-09-05'),
 ('23 mar 1981', '1981-03-23'),
 ('1 november 1992', '1992-11-01'),
 ('wednesday september 11 1985', '1985-09-11'),
 ('monday october 31 1983', '1983-10-31'),
 ('february 16 1981', '1981-02-16'),
 ('january 28 1981', '1981-01-28'),
 ('monday august 14 1989', '1989-08-14'),
 ('20 march 1980', '1980-03-20'),
 ('friday july 21 2006', '2006-07-21'),
 ('march 1 1976', '1976-03-01'),
 ('12 may 2005', '2005-05-12'),
 ('saturday may 6 2017', '2017-05-06'),
 ('tuesday march 24 1970', '1970-03-24'),
 ('saturday december 22 1979', '1979-12-22'),
 ('saturday march 21 1970', '1970-03-21'),
 ('friday october 3 2014', '2014-10-03'),
 ('saturday october 4 2003', '2003-10-04'),
 ('saturday july 31 1982', '1982-07-31'),
 ('thursday may 5 2011', '2011-05-05'),
 ('10 july 1976', '1976-07-10'),
 ('december 26 1987', '1987-12-26'),
 ('17 may 2004', '2004-05-17'),
 ('august 21 1997', '1997-08-21'),
 ('7/2/74', '1974-07-02'),
 ('saturday may 12 2001', '2001-05-12'),
 ('5/11/98', '1998-05-11'),
 ('may 20 1982', '1982-05-20'),
 ('22 jul 1986', '1986-07-22'),
 ('sunday july 18 1982', '1982-07-18'),
 ('9 11 71', '1971-11-09'),
 ('thursday may 18 1995', '1995-05-18'),
 ('saturday june 27 1992', '1992-06-27'),
 ('22 dec 1981', '1981-12-22'),
 ('tuesday november 12 1996', '1996-11-12'),
 ('february 7 1982', '1982-02-07'),
 ('10 february 1982', '1982-02-10'),
 ('25 nov 2008', '2008-11-25'),
 ('friday april 8 2016', '2016-04-08'),
 ('friday april 8 2005', '2005-04-08'),
 ('wednesday december 10 1986', '1986-12-10'),
 ('2/14/98', '1998-02-14'),
 ('friday december 3 2004', '2004-12-03'),
 ('monday january 30 2017', '2017-01-30'),
 ('sunday may 31 1998', '1998-05-31'),
 ('wednesday february 12 1992', '1992-02-12'),
 ('monday march 6 1978', '1978-03-06'),
 ('saturday august 10 1974', '1974-08-10'),
 ('22 oct 2013', '2013-10-22'),
 ('may 3 2001', '2001-05-03'),
 ('11 apr 1983', '1983-04-11'),
 ('saturday september 29 2012', '2012-09-29'),
 ('12 apr 2012', '2012-04-12'),
 ('15 nov 2008', '2008-11-15'),
 ('september 27 1983', '1983-09-27'),
 ('11 mar 1979', '1979-03-11'),
 ('saturday february 18 2006', '2006-02-18'),
 ('friday november 15 1985', '1985-11-15'),
 ('june 23 1992', '1992-06-23'),
 ('23 august 2008', '2008-08-23'),
 ('22 november 1989', '1989-11-22'),
 ('13.07.78', '1978-07-13'),
 ('friday august 18 2006', '2006-08-18'),
 ('23 september 2004', '2004-09-23'),
 ('9 03 17', '2017-03-09'),
 ('30 aug 2015', '2015-08-30'),
 ('friday january 11 1974', '1974-01-11'),
 ('09.09.87', '1987-09-09'),
 ('tuesday january 19 1999', '1999-01-19'),
 ('30 dec 1972', '1972-12-30'),
 ('saturday october 8 1994', '1994-10-08'),
 ('monday february 28 2005', '2005-02-28'),
 ('20 jun 2006', '2006-06-20'),
 ('friday january 23 2009', '2009-01-23'),
 ('wednesday april 27 1977', '1977-04-27'),
 ('28 october 2012', '2012-10-28'),
 ('17 aug 1974', '1974-08-17'),
 ('august 17 1980', '1980-08-17'),
 ('april 6 1995', '1995-04-06'),
 ('mar 21 2018', '2018-03-21'),
 ('thursday march 14 2013', '2013-03-14'),
 ('28 may 1972', '1972-05-28'),
 ('sep 16 1988', '1988-09-16'),
 ('tuesday march 21 2000', '2000-03-21'),
 ('4 sep 2016', '2016-09-04'),
 ('2 february 1995', '1995-02-02'),
 ('05 may 1997', '1997-05-05'),
 ('wednesday november 28 1990', '1990-11-28'),
 ('26 july 2000', '2000-07-26'),
 ('july 15 2011', '2011-07-15'),
 ('monday december 28 1987', '1987-12-28'),
 ('saturday march 23 1991', '1991-03-23'),
 ('july 8 2003', '2003-07-08'),
 ('10 september 2002', '2002-09-10'),
 ('jun 5 1973', '1973-06-05'),
 ('saturday january 16 1988', '1988-01-16'),
 ('27.04.00', '2000-04-27'),
 ('31 december 1971', '1971-12-31'),
 ('december 12 1984', '1984-12-12'),
 ('friday june 25 1993', '1993-06-25'),
 ('friday april 6 1979', '1979-04-06'),
 ('friday february 20 1970', '1970-02-20'),
 ('5 january 2016', '2016-01-05'),
 ('28 07 12', '2012-07-28'),
 ('friday august 29 1975', '1975-08-29'),
 ('monday january 31 1972', '1972-01-31'),
 ('23.07.77', '1977-07-23'),
 ('31 dec 2010', '2010-12-31'),
 ('16 oct 1982', '1982-10-16'),
 ('jan 5 1997', '1997-01-05'),
 ('tuesday may 20 2003', '2003-05-20'),
 ('17 may 1982', '1982-05-17'),
 ('7/21/88', '1988-07-21'),
 ('monday october 4 1993', '1993-10-04'),
 ('sunday march 11 1984', '1984-03-11'),
 ('tuesday june 5 1990', '1990-06-05'),
 ('6/16/91', '1991-06-16'),
 ('june 3 1996', '1996-06-03'),
 ('20 february 1975', '1975-02-20'),
 ('december 23 2011', '2011-12-23'),
 ('6/22/90', '1990-06-22'),
 ('thursday january 26 1995', '1995-01-26'),
 ('2 10 72', '1972-10-02'),
 ('monday july 13 1998', '1998-07-13'),
 ('monday november 29 1982', '1982-11-29'),
 ('03 dec 1980', '1980-12-03'),
 ('monday july 28 1975', '1975-07-28'),
 ('friday september 21 1979', '1979-09-21'),
 ('saturday november 10 1990', '1990-11-10'),
 ('monday october 21 1985', '1985-10-21'),
 ('tuesday august 25 1992', '1992-08-25'),
 ('15.11.98', '1998-11-15'),
 ('saturday september 3 1983', '1983-09-03'),
 ('friday december 11 1970', '1970-12-11'),
 ('march 14 1980', '1980-03-14'),
 ('26 09 77', '1977-09-26'),
 ('thursday december 23 2004', '2004-12-23'),
 ('wednesday february 23 1972', '1972-02-23'),
 ('mar 17 1993', '1993-03-17'),
 ('7 sep 1996', '1996-09-07'),
 ('wednesday september 25 1991', '1991-09-25'),
 ('wednesday october 11 1972', '1972-10-11'),
 ('june 4 1986', '1986-06-04'),
 ('monday october 11 1976', '1976-10-11'),
 ('tuesday december 24 2002', '2002-12-24'),
 ('saturday february 9 1980', '1980-02-09'),
 ('monday may 11 2009', '2009-05-11'),
 ('14 jan 1984', '1984-01-14'),
 ('friday august 21 1987', '1987-08-21'),
 ('10/11/08', '2008-10-11'),
 ('friday march 24 2006', '2006-03-24'),
 ('saturday june 4 1994', '1994-06-04'),
 ('11 oct 1980', '1980-10-11'),
 ('may 2 1989', '1989-05-02'),
 ('wednesday august 2 1972', '1972-08-02'),
 ('wednesday march 31 1976', '1976-03-31'),
 ('tuesday may 25 1976', '1976-05-25'),
 ('nov 26 2005', '2005-11-26'),
 ('friday february 10 1984', '1984-02-10'),
 ('thursday may 24 2007', '2007-05-24'),
 ('23 apr 2004', '2004-04-23'),
 ('wednesday september 24 2014', '2014-09-24'),
 ('28 nov 1997', '1997-11-28'),
 ('sunday august 28 2005', '2005-08-28'),
 ('thursday january 14 1971', '1971-01-14'),
 ('21 may 2005', '2005-05-21'),
 ('26 april 1980', '1980-04-26'),
 ('saturday january 16 2010', '2010-01-16'),
 ('monday march 6 2006', '2006-03-06'),
 ('21.02.92', '1992-02-21'),
 ('thursday january 7 2010', '2010-01-07'),
 ('feb 21 1981', '1981-02-21'),
 ('february 17 2001', '2001-02-17'),
 ('thursday march 19 1998', '1998-03-19'),
 ('1 dec 1999', '1999-12-01'),
 ('friday september 3 1971', '1971-09-03'),
 ('19 april 1995', '1995-04-19'),
 ('1 feb 2015', '2015-02-01'),
 ('november 11 1971', '1971-11-11'),
 ('7 jun 1996', '1996-06-07'),
 ('21 jan 1994', '1994-01-21'),
 ('11/17/15', '2015-11-17'),
 ('23 oct 2006', '2006-10-23'),
 ('sunday october 12 2014', '2014-10-12'),
 ('10 jun 2010', '2010-06-10'),
 ('28 february 1971', '1971-02-28'),
 ('sunday september 22 1991', '1991-09-22'),
 ('31 dec 2001', '2001-12-31'),
 ('wednesday october 13 1999', '1999-10-13'),
 ('10 february 1973', '1973-02-10'),
 ('17 sep 1991', '1991-09-17'),
 ('26 april 1991', '1991-04-26'),
 ('7/3/96', '1996-07-03'),
 ('tuesday april 24 1990', '1990-04-24'),
 ('july 16 1978', '1978-07-16'),
 ('11/3/95', '1995-11-03'),
 ('sunday june 22 2008', '2008-06-22'),
 ('sunday may 13 2012', '2012-05-13'),
 ('november 10 1973', '1973-11-10'),
 ('21 october 2008', '2008-10-21'),
 ('june 22 1977', '1977-06-22'),
 ('31 01 03', '2003-01-31'),
 ('1/29/78', '1978-01-29'),
 ('saturday july 24 1976', '1976-07-24'),
 ('02 nov 2011', '2011-11-02'),
 ('6 november 1981', '1981-11-06'),
 ('apr 6 1972', '1972-04-06'),
 ('tuesday june 26 1973', '1973-06-26'),
 ('monday january 7 1991', '1991-01-07'),
 ('monday september 24 1984', '1984-09-24'),
 ('saturday september 24 2005', '2005-09-24'),
 ('sunday july 25 1976', '1976-07-25'),
 ('wednesday may 2 2001', '2001-05-02'),
 ('23 dec 2003', '2003-12-23'),
 ('3 12 01', '2001-12-03'),
 ('jan 3 1974', '1974-01-03'),
 ('23 oct 1998', '1998-10-23'),
 ('saturday december 22 1984', '1984-12-22'),
 ('11 feb 1985', '1985-02-11'),
 ('thursday june 4 1992', '1992-06-04'),
 ('monday january 12 1981', '1981-01-12'),
 ('29 01 96', '1996-01-29'),
 ('saturday january 9 2010', '2010-01-09'),
 ('dec 21 2006', '2006-12-21'),
 ('jun 13 1986', '1986-06-13'),
 ('wednesday september 7 2016', '2016-09-07'),
 ('saturday february 2 2002', '2002-02-02'),
 ('12 apr 1982', '1982-04-12'),
 ('friday march 9 1984', '1984-03-09'),
 ('6 september 2007', '2007-09-06'),
 ('01 feb 2009', '2009-02-01'),
 ('05 jul 2007', '2007-07-05'),
 ('jul 17 2013', '2013-07-17'),
 ('21 jul 1984', '1984-07-21'),
 ('wednesday november 5 1980', '1980-11-05'),
 ('tuesday october 13 2015', '2015-10-13'),
 ('friday december 29 2000', '2000-12-29'),
 ('26.12.70', '1970-12-26'),
 ('thursday april 10 2014', '2014-04-10'),
 ('thursday april 7 1983', '1983-04-07'),
 ('25 dec 1974', '1974-12-25'),
 ('30 september 1974', '1974-09-30'),
 ('sunday february 24 2008', '2008-02-24'),
 ('april 29 1978', '1978-04-29'),
 ('05 jun 1976', '1976-06-05'),
 ('tuesday january 19 1988', '1988-01-19'),
 ('tuesday july 29 2008', '2008-07-29'),
 ('15 january 1986', '1986-01-15'),
 ('14 jul 1984', '1984-07-14'),
 ('22 november 1988', '1988-11-22'),
 ('2 may 1985', '1985-05-02'),
 ('thursday november 13 2003', '2003-11-13'),
 ('friday march 10 1995', '1995-03-10'),
 ('november 21 2016', '2016-11-21'),
 ('26.05.00', '2000-05-26'),
 ('17 february 2015', '2015-02-17'),
 ('6/18/97', '1997-06-18'),
 ('4 april 2008', '2008-04-04'),
 ('monday december 15 1986', '1986-12-15'),
 ('april 12 2014', '2014-04-12'),
 ('august 30 2000', '2000-08-30'),
 ('29 april 2004', '2004-04-29'),
 ('thursday may 19 1977', '1977-05-19'),
 ('tuesday april 5 2005', '2005-04-05'),
 ('wednesday january 19 1972', '1972-01-19'),
 ('25 nov 2004', '2004-11-25'),
 ('thursday october 5 2006', '2006-10-05'),
 ('monday may 2 2016', '2016-05-02'),
 ('monday january 16 1995', '1995-01-16'),
 ('thursday april 3 1986', '1986-04-03'),
 ('14 mar 1997', '1997-03-14'),
 ('friday july 25 2003', '2003-07-25'),
 ('10.08.16', '2016-08-10'),
 ('august 11 1975', '1975-08-11'),
 ('7 september 1998', '1998-09-07'),
 ('september 6 2001', '2001-09-06'),
 ('friday july 22 1977', '1977-07-22'),
 ('21 april 1992', '1992-04-21'),
 ('wednesday december 17 1986', '1986-12-17'),
 ('25 march 2000', '2000-03-25'),
 ('1 september 1990', '1990-09-01'),
 ('24 nov 1998', '1998-11-24'),
 ('saturday july 12 2008', '2008-07-12'),
 ('25 jun 1978', '1978-06-25'),
 ('8/26/81', '1981-08-26'),
 ('31 oct 1984', '1984-10-31'),
 ('24 december 2011', '2011-12-24'),
 ('march 10 1996', '1996-03-10'),
 ('thursday november 5 1987', '1987-11-05'),
 ('thursday october 23 2008', '2008-10-23'),
 ('thursday april 18 2013', '2013-04-18'),
 ('23 dec 1981', '1981-12-23'),
 ('october 23 2012', '2012-10-23'),
 ('may 20 1970', '1970-05-20'),
 ('24 feb 2005', '2005-02-24'),
 ('20 october 1988', '1988-10-20'),
 ('saturday august 14 1971', '1971-08-14'),
 ('wednesday august 14 2002', '2002-08-14'),
 ('wednesday august 12 1992', '1992-08-12'),
 ('19 march 2017', '2017-03-19'),
 ('friday december 14 2012', '2012-12-14'),
 ('21 sep 1983', '1983-09-21'),
 ('28 jul 2012', '2012-07-28'),
 ('thursday july 26 1990', '1990-07-26'),
 ('wednesday december 1 1971', '1971-12-01'),
 ('thursday january 23 1997', '1997-01-23'),
 ('23.12.94', '1994-12-23'),
 ('28 08 84', '1984-08-28'),
 ('tuesday march 11 2008', '2008-03-11'),
 ('friday january 16 1987', '1987-01-16'),
 ('06 sep 1985', '1985-09-06'),
 ('12 april 1976', '1976-04-12'),
 ('sunday november 20 1983', '1983-11-20'),
 ('6 february 1987', '1987-02-06'),
 ('2/2/08', '2008-02-02'),
 ('26 may 1970', '1970-05-26'),
 ('16.02.71', '1971-02-16'),
 ('19.04.80', '1980-04-19'),
 ('monday may 5 2008', '2008-05-05'),
 ('8/10/09', '2009-08-10'),
 ('27 jan 1979', '1979-01-27'),
 ('thursday may 7 1992', '1992-05-07'),
 ('july 4 1984', '1984-07-04'),
 ('27 september 1978', '1978-09-27'),
 ('thursday june 23 2011', '2011-06-23'),
 ('24 may 2012', '2012-05-24'),
 ('saturday november 10 1990', '1990-11-10'),
 ('9/20/04', '2004-09-20'),
 ('14.06.89', '1989-06-14'),
 ('wednesday december 22 1971', '1971-12-22'),
 ('thursday april 19 1984', '1984-04-19'),
 ('saturday march 6 1999', '1999-03-06'),
 ('7 october 1996', '1996-10-07'),
 ('saturday june 4 2016', '2016-06-04'),
 ('thursday july 16 2009', '2009-07-16'),
 ('april 29 1997', '1997-04-29'),
 ('saturday december 28 2013', '2013-12-28'),
 ('wednesday july 31 2013', '2013-07-31'),
 ('12 december 2014', '2014-12-12'),
 ('12/15/99', '1999-12-15'),
 ('11/4/08', '2008-11-04'),
 ('friday april 11 2008', '2008-04-11'),
 ('19 jan 1989', '1989-01-19'),
 ('02 mar 2004', '2004-03-02'),
 ('wednesday march 22 1989', '1989-03-22'),
 ('saturday july 22 2006', '2006-07-22'),
 ('monday december 23 1974', '1974-12-23'),
 ('sunday october 19 2014', '2014-10-19'),
 ('25 06 02', '2002-06-25'),
 ('7 10 17', '2017-10-07'),
 ('saturday november 2 2002', '2002-11-02'),
 ('28 feb 2014', '2014-02-28'),
 ('saturday october 18 1980', '1980-10-18'),
 ('9/19/98', '1998-09-19'),
 ('monday march 26 1973', '1973-03-26'),
 ('15 nov 2017', '2017-11-15'),
 ('thursday september 9 1976', '1976-09-09'),
 ('february 11 1978', '1978-02-11'),
 ('16 feb 1988', '1988-02-16'),
 ('tuesday february 24 2015', '2015-02-24'),
 ('2 june 1991', '1991-06-02'),
 ('1 february 1998', '1998-02-01'),
 ('13.09.96', '1996-09-13'),
 ('june 13 2002', '2002-06-13'),
 ('23 april 1976', '1976-04-23'),
 ('10 jul 1996', '1996-07-10'),
 ('4 november 2016', '2016-11-04'),
 ('wednesday september 18 2013', '2013-09-18'),
 ('31 mar 1978', '1978-03-31'),
 ('thursday april 29 1999', '1999-04-29'),
 ('23 august 1985', '1985-08-23'),
 ('march 28 2012', '2012-03-28'),
 ('july 1 1970', '1970-07-01'),
 ('23 mar 2001', '2001-03-23'),
 ('august 1 1980', '1980-08-01'),
 ('30 aug 2012', '2012-08-30'),
 ('22 december 1970', '1970-12-22'),
 ('wednesday march 23 1994', '1994-03-23'),
 ('23 nov 1980', '1980-11-23'),
 ('mar 14 2016', '2016-03-14'),
 ('may 13 1988', '1988-05-13'),
 ('wednesday october 31 1979', '1979-10-31'),
 ('09.05.96', '1996-05-09'),
 ('sunday november 30 1980', '1980-11-30'),
 ('tuesday march 26 1991', '1991-03-26'),
 ('december 12 1991', '1991-12-12'),
 ('friday september 7 2012', '2012-09-07'),
 ('20 nov 2010', '2010-11-20'),
 ('08.07.91', '1991-07-08'),
 ('sunday april 4 1999', '1999-04-04'),
 ('01 sep 1972', '1972-09-01'),
 ('february 7 1994', '1994-02-07'),
 ('wednesday september 10 1986', '1986-09-10'),
 ('january 1 2017', '2017-01-01'),
 ('13 november 2010', '2010-11-13'),
 ('sunday february 25 2001', '2001-02-25'),
 ('27.10.71', '1971-10-27'),
 ('10 aug 1993', '1993-08-10'),
 ('monday september 7 2015', '2015-09-07'),
 ('8 09 96', '1996-09-08'),
 ('11/17/03', '2003-11-17'),
 ('2 may 1979', '1979-05-02'),
 ('sunday april 24 2011', '2011-04-24'),
 ('15 june 1995', '1995-06-15'),
 ('12/14/16', '2016-12-14'),
 ('thursday august 21 2008', '2008-08-21'),
 ('sunday april 29 1990', '1990-04-29'),
 ('april 4 2007', '2007-04-04'),
 ('tuesday january 2 1979', '1979-01-02'),
 ('sunday december 14 2003', '2003-12-14'),
 ('wednesday september 20 2000', '2000-09-20'),
 ('tuesday january 31 2017', '2017-01-31'),
 ('monday october 5 1970', '1970-10-05'),
 ('monday september 24 2001', '2001-09-24'),
 ('6 january 1995', '1995-01-06'),
 ('14 09 85', '1985-09-14'),
 ('wednesday november 12 1997', '1997-11-12'),
 ('8 feb 2002', '2002-02-08'),
 ('may 5 1985', '1985-05-05'),
 ('tuesday december 20 2011', '2011-12-20'),
 ('sunday august 1 2004', '2004-08-01'),
 ('february 21 1993', '1993-02-21'),
 ('15 06 03', '2003-06-15'),
 ('9 february 1990', '1990-02-09'),
 ('7/3/10', '2010-07-03'),
 ('monday july 22 1985', '1985-07-22'),
 ('april 9 1998', '1998-04-09'),
 ('wednesday october 2 1991', '1991-10-02'),

In [3]:
#human_vocab_file = open('human_vocab.pickle', 'wb')
#pickle.dump(human_vocab, human_vocab_file)
#human_vocab_file.close()

human_vocab_file = open('dataset/human_vocab.pickle', 'rb')
human_vocab = pickle.load(human_vocab_file)
human_vocab_file.close()

In [4]:
#machine_vocab_file = open('machine_vocab.pickle', 'wb')
#pickle.dump(machine_vocab, machine_vocab_file)
#machine_vocab_file.close()

machine_vocab_file = open('dataset/machine_vocab.pickle', 'rb')
machine_vocab = pickle.load(machine_vocab_file)
machine_vocab_file.close()

In [5]:
#inv_machine_vocab_file = open('inv_machine_vocab.pickle', 'wb')
#pickle.dump(inv_machine_vocab, inv_machine_vocab_file)
#inv_machine_vocab_file.close()

inv_machine_vocab_file = open('dataset/inv_machine_vocab.pickle', 'rb')
inv_machine_vocab = pickle.load(inv_machine_vocab_file)  # variables come out in the order you put them in
inv_machine_vocab_file.close()

In [6]:
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.

In [7]:
X = []
Y = []
for i, date in enumerate(dates):
    index_x = []
    index_y = []
    for j, character in enumerate(date[0]):
        index_x.append(human_vocab.get(character))
    X.append(index_x)
    for j, character in enumerate(date[1]):
        index_y.append(machine_vocab.get(character))
    Y.append(index_y)
    
X = pad_sequences(X, maxlen=30, padding="post", value=36.)

In [8]:
input_encoding = human_vocab
output_encoding = machine_vocab
input_decoding = {v: k for k, v in input_encoding.items()}
output_decoding = {v: k for k, v in output_encoding.items()}

In [9]:
import numpy as np

In [11]:
Xoh = np.zeros(shape=(len(X), 30, 37))
for i, data in enumerate(X): 
    for j, character in enumerate(data): 
        Xoh[i, j, character] = 1.

In [12]:
Yoh = np.zeros(shape=(len(Y), 10, 11))
for i, data in enumerate(Y): 
    for j, character in enumerate(data): 
        Yoh[i, j, character] = 1.

In [13]:
index = 0
print("Source date:", dates[index][0])
print("Target date:", dates[index][1])
print()
print("Source after preprocessing (indices):", X[index])
print("Target after preprocessing (indices):", Y[index])
print()
print("Source after preprocessing (one-hot):", Xoh[index])
print("Target after preprocessing (one-hot):", Yoh[index])

Source date: 9 may 1998
Target date: 1998-05-09

Source after preprocessing (indices): [12  0 24 13 34  0  4 12 12 11 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36
 36 36 36 36 36]
Target after preprocessing (indices): [2, 10, 10, 9, 0, 1, 6, 0, 1, 10]

Source after preprocessing (one-hot): [[ 0.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ...,
 [ 0.  0.  0. ...,  0.  0.  1.]
 [ 0.  0.  0. ...,  0.  0.  1.]
 [ 0.  0.  0. ...,  0.  0.  1.]]
Target after preprocessing (one-hot): [[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]

In [14]:
X[index]

array([12,  0, 24, 13, 34,  0,  4, 12, 12, 11, 36, 36, 36, 36, 36, 36, 36,
       36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36])

In [57]:
Xoh_file = open('Xoh.pickle', 'wb')
pickle.dump(Xoh, Xoh_file)
Xoh_file.close()

Yoh_file = open('Yoh.pickle', 'wb')
pickle.dump(Yoh, Yoh_file)
Yoh_file.close()

In [15]:
X_file = open('X.pickle', 'wb')
pickle.dump(X, X_file)
X_file.close()

Y_file = open('Y.pickle', 'wb')
pickle.dump(Y, Y_file)
Y_file.close()